CREATE TABLE "public"."sport" (
    "id" bigint DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "name" character varying(255) NOT NULL,
    CONSTRAINT "sport_pkey" PRIMARY KEY ("id")
) WITH (oids = false);


CREATE TABLE "public"."user" (
    "id" bigint DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "password" character varying(255) NOT NULL,
    "profile_picture" character varying(255),
    "registered_at" timestamp NOT NULL,
    "roles" character varying(255) NOT NULL,
    "updated_at" timestamp NOT NULL,
    "username" character varying(500) NOT NULL,
    CONSTRAINT "uq_user_username" UNIQUE ("username"),
    CONSTRAINT "user_pkey" PRIMARY KEY ("id")
) WITH (oids = false);


CREATE TABLE "public"."client" (
    "city" character varying(300),
    "complement" character varying(300),
    "district" character varying(300),
    "federal_unit" character varying(300),
    "public_place" character varying(300),
    "zip_code" character varying(50),
    "email" character varying(500),
    "name" character varying(500),
    "phone" character varying(50),
    "is_whatsapp" boolean,
    "registered_at" timestamp NOT NULL,
    "updated_at" timestamp NOT NULL,
    "id" bigint NOT NULL,
    CONSTRAINT "client_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "fk_client_id" FOREIGN KEY (id) REFERENCES "user"(id) NOT DEFERRABLE
) WITH (oids = false);


CREATE TABLE "public"."gym" (
    "city" character varying(300),
    "complement" character varying(300),
    "district" character varying(300),
    "federal_unit" character varying(300),
    "public_place" character varying(300),
    "zip_code" character varying(50),
    "biography" character varying(1000),
    "email" character varying(500),
    "name" character varying(500),
    "phone" character varying(50),
    "is_whatsapp" boolean,
    "instagram" character varying(255),
    "registered_at" timestamp NOT NULL,
    "updated_at" timestamp NOT NULL,
    "id" bigint NOT NULL,
    CONSTRAINT "gym_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "fk_gym_id" FOREIGN KEY (id) REFERENCES "user"(id) NOT DEFERRABLE
) WITH (oids = false);


CREATE TABLE "public"."personal_trainer" (
    "acting_city" character varying(300),
    "biography" character varying(1000),
    "email" character varying(500),
    "name" character varying(500),
    "phone" character varying(50),
    "is_whatsapp" boolean,
    "instagram" character varying(255),
    "registered_at" timestamp NOT NULL,
    "updated_at" timestamp NOT NULL,
    "id" bigint NOT NULL,
    CONSTRAINT "personal_trainer_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "fk_personal_trainer_id" FOREIGN KEY (id) REFERENCES "user"(id) NOT DEFERRABLE
) WITH (oids = false);


CREATE TABLE "public"."gym_gallery_pictures" (
    "gym_id" bigint NOT NULL,
    "gallery_pictures" character varying(255),
    CONSTRAINT "fk_gym_gallery_pictures_gym_id" FOREIGN KEY (gym_id) REFERENCES gym(id) NOT DEFERRABLE
) WITH (oids = false);


CREATE TABLE "public"."gym_sports" (
    "gym_id" bigint NOT NULL,
    "sport_id" bigint NOT NULL,
    CONSTRAINT "gym_sports_pkey" PRIMARY KEY ("gym_id", "sport_id"),
    CONSTRAINT "fk_gym_sports_gym_id" FOREIGN KEY (gym_id) REFERENCES gym(id) NOT DEFERRABLE,
    CONSTRAINT "fk_gym_sports_sport_id" FOREIGN KEY (sport_id) REFERENCES sport(id) NOT DEFERRABLE
) WITH (oids = false);


CREATE TABLE "public"."personal_trainer_gallery_pictures" (
    "personal_trainer_id" bigint NOT NULL,
    "gallery_pictures" character varying(255),
    CONSTRAINT "fk_personal_trainer_gallery_pictures_personal_trainer_id" FOREIGN KEY (personal_trainer_id) REFERENCES personal_trainer(id) NOT DEFERRABLE
) WITH (oids = false);


CREATE TABLE "public"."personal_trainer_sports" (
    "personal_trainer_id" bigint NOT NULL,
    "sport_id" bigint NOT NULL,
    CONSTRAINT "personal_trainer_sports_pkey" PRIMARY KEY ("personal_trainer_id", "sport_id"),
    CONSTRAINT "fk_personal_trainer_sports_personal_trainer_id" FOREIGN KEY (personal_trainer_id) REFERENCES personal_trainer(id) NOT DEFERRABLE,
    CONSTRAINT "fk_personal_trainer_sports_sport_id" FOREIGN KEY (sport_id) REFERENCES sport(id) NOT DEFERRABLE
) WITH (oids = false);
