server:
  port: ${PORT}
  error:
    whitelabel:
      enabled: false

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

itrain:
  jws:
    secret: ${ITRAIN_JWS_SECRET}
    expiration-time: 864000000
  swagger:
    base-package: com.itrain
    app-name: ITrain App
    app-version: 0.0.1
    contact-name: ITrain Team
    contact-site: https://itrain.com.br
    contact-email: bzappcomercial@gmail.com
    api-description: ITrain API for all
  student:
    base-url: ${ITRAIN_STUDENT_BASE_URL}
  gym:
    base-url: ${ITRAIN_GYM_BASE_URL}
  personal-trainer:
    base-url: ${ITRAIN_PERSONAL_TRAINER_BASE_URL}
  sport:
    base-url: ${ITRAIN_SPORT_BASE_URL}
